- hosts: code
  tasks:
   - name: Ping my hosts
     ping:

   - name: Gather the package facts
     ansible.builtin.package_facts:
       manager: auto

   - name: "Only run update_cache is last one is more than 86400 seconds old"
     ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 43200

   - name: "Update and install required packages"
     ansible.builtin.apt:
      only_upgrade: yes
      state: latest
      pkg:
       - python3
       - apache2
       - samba

   - name: "Update all packages using apt"
     ansible.builtin.apt:
       update_cache: true
       upgrade: dist
       
